reading_folder: "readings"

subject_id: "24f55a34-9949-8006-8dec-fac03212190b"
assignments_id: "24f55a34-9949-8045-b62d-df9d8cc37311"
# reading_template_id: "17255a349949814a8d35d76a8ac0fc93"

prompts:
  - name: "default_reading_prompt"
    content: |
      请对以下教科书文档进行深入分析，并提供以下内容。请确保每一部分都详尽、清晰，并尽可能多地包含关键信息和细节。

      1.  **要点 (Key Points)**：以项目符号列表的形式，直接并全面地列出文档中所有的核心信息。请重点提取并解释**关键概念、重要定义、核心原理和关键术语**，特别是那些在原文中以**粗体**或其他方式突出显示的内容。每一个要点都应该是独立的、清晰的，并包含足够的上下文或解释，而不仅仅是单个词语的罗列。

      2.  **笔记 (Notes)**：以段落形式，对文档的关键信息进行详细的阐述和补充。请在这里解释各个要点之间的逻辑关系、层次结构和相互联系。对重要的理论或模型进行更深入的解释，并说明其在实际中的应用或意义。此部分应作为对“要点”的深化和扩展，而不是个人反思。

      3.  **摘要 (Summary)**：以一个或多个结构清晰的段落，提供一份全面而详尽的文档内容总结。这份摘要需要涵盖所有在“要点”中列出的信息，并按照原文的逻辑顺序进行组织。请确保摘要的长度足够，能够完整地再现文档的核心内容，包括主要的理论、支撑这些理论的证据或例子，以及最终得出的结论。摘要应力求内容的完整性和信息的准确性，避免遗漏任何关键细节。

      请确保输出格式如下，并使用明确的标题分隔每个部分：

      **要点**
      * [直接列出并解释第一个要点，例如：**术语A**: 它的定义和重要性。]
      * [直接列出并解释第二个要点，例如：**原理B**: 它的内容和应用。]
      * [直接列出并解释第三个要点...]

      **笔记**
      [在此处提供对要点之间逻辑关系、层次结构和相互联系的详细阐述，以及对关键理论的深入解释。]

      **摘要**
      [在此处提供一个详尽、全面、结构清晰的段落式总结，确保涵盖所有关键信息，并保持内容的完整性和准确性。]
  - name: "secondary_example_prompt"
    content: |
      请对以下教科书文档进行深入分析，并提供以下内容。请确保每一部分都详尽、清晰，并尽可能多地包含关键信息和细节。

      1.  **要点 (Key Points)**：以项目符号列表的形式，直接并全面地列出文档中所有的核心信息。请重点提取并解释**关键概念、重要定义、核心原理和关键术语**，特别是那些在原文中以**粗体**或其他方式突出显示的内容。每一个要点都应该是独立的、清晰的，并包含足够的上下文或解释，而不仅仅是单个词语的罗列。

      2.  **笔记 (Notes)**：以段落形式，对文档的关键信息进行详细的阐述和补充。请在这里解释各个要点之间的逻辑关系、层次结构和相互联系。对重要的理论或模型进行更深入的解释，并说明其在实际中的应用或意义。此部分应作为对“要点”的深化和扩展，而不是个人反思。

      3.  **摘要 (Summary)**：以一个或多个结构清晰的段落，提供一份全面而详尽的文档内容总结。这份摘要需要涵盖所有在“要点”中列出的信息，并按照原文的逻辑顺序进行组织。请确保摘要的长度足够，能够完整地再现文档的核心内容，包括主要的理论、支撑这些理论的证据或例子，以及最终得出的结论。摘要应力求内容的完整性和信息的准确性，避免遗漏任何关键细节。

      请确保输出格式如下，并使用明确的标题分隔每个部分：

      **要点**
      * [直接列出并解释第一个要点，例如：**术语A**: 它的定义和重要性。]
      * [直接列出并解释第二个要点，例如：**原理B**: 它的内容和应用。]
      * [直接列出并解释第三个要点...]

      **笔记**
      [在此处提供对要点之间逻辑关系、层次结构和相互联系的详细阐述，以及对关键理论的深入解释。]

      **摘要**
      [在此处提供一个详尽、全面、结构清晰的段落式总结，确保涵盖所有关键信息，并保持内容的完整性和准确性。]
